name: CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Builds the Docker image
        run: docker build ./ -t govnft/app

      - name: Runs code QA and tests
        env:
          ETHERSCAN_API_KEY: ${{secrets.ETHERSCAN_API_KEY}}
        run: docker run --rm --env-file=.env.example -e ETHERSCAN_API_KEY="$ETHERSCAN_API_KEY" -t govnft/app sh -c 'yarn build'
