name: CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.14.x

      - name: Install dependencies
        uses: borales/actions-yarn@3766bb1335b98fb13c60eaf358fe20811b730a88
        with:
          cmd: install --frozen-lockfile

      - name: Update submodules
        run: git submodule update --init --recursive

      - name: Build app with .example env
        env:
          ETHERSCAN_API_KEY: ${{secrets.ETHERSCAN_API_KEY}}
          MODE: example
        uses: borales/actions-yarn@3766bb1335b98fb13c60eaf358fe20811b730a88
        with:
          cmd: build:ci